const {chromium}=require('playwright');const fs=require('node:fs');const assert=require('node:assert/strict');
const dir=process.env.HW_EVIDENCE||'/home/user/handwriting-fix-evidence';
const cases={short:'<p>رحمة تكتب حكايتها العربية بوضوح. الأرقام ١٢٣٤٥ و12345.</p>',rich:'<h2>عنوان فرعي</h2><p><span data-editor-font="amiri" style="font-family:Amiri;font-weight:400">سطر بخط عربي</span> <mark style="background-color:#ffe600;color:#000">كلمات مظللة</mark> <strong>ونص عريض</strong></p><p dir="rtl">نص ثانٍ مع <em>ميلان</em> و<u>تسطير</u>.</p>',long:Array.from({length:36},(_,i)=>`<p>${i+1}. كتبت رحمة حكاية عن الأمل والذاكرة، واحتفظت بكل كلمة في دفترها. سطر عربي للتأكد من الصفحات وعدم اختفاء النص.</p>`).join('')};
(async()=>{const b=await chromium.launch();const results=[];try{for(const [name,url] of [['before','http://localhost:3171'],['after','http://localhost:3170']].filter(([side])=>!process.env.PDF_SIDE||side===process.env.PDF_SIDE)){
 const p=await b.newPage({viewport:{width:794,height:1123},deviceScaleFactor:1});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url+'/tools/handwriting-fix-check/');await p.waitForFunction(()=>!!window.__hwBaseline);
 await p.addStyleTag({url:url+'/components/EditorFonts.css'});
 const fonts=await p.evaluate(async()=>{const {EDITOR_FONTS,loadEditorFont}=await import('/lib/editor-fonts.ts');const amiri=EDITOR_FONTS.find(f=>f.id==='amiri');await loadEditorFont(amiri,400);await loadEditorFont(amiri,700);return Array.from(document.fonts).filter(f=>f.family==='Amiri'&&f.status==='loaded').map(f=>f.weight);});assert(fonts.includes('400')&&fonts.includes('700'));
 for(const [id,content]of Object.entries(cases).filter(([id])=>!process.env.PDF_CASE||id===process.env.PDF_CASE)){console.log('Exporting',name,id);
  const data=await p.evaluate(async content=>{const{exportStoryToPdf}=await import('/lib/pdf-export.ts');const blob=await exportStoryToPdf('تجربة تصدير عربية',content,{fontSize:20,fontWeight:400,textAlign:'right',textColor:'#121A1B',paperStyleIndex:0},{bg:'#fff',text:'#121A1B',secondary:'#444'});return{bytes:Array.from(new Uint8Array(await blob.arrayBuffer())),type:blob.type,remaining:document.querySelectorAll('.html2pdf__overlay').length};},content);
  const bytes=Buffer.from(data.bytes);const producer=bytes.toString('latin1').match(/\/Producer \(([^)]+)\)/)?.[1];if(name==='after')assert.equal(producer,'jsPDF 4.2.1');assert(bytes.subarray(0,5).equals(Buffer.from('%PDF-')));assert.equal(data.remaining,0);fs.writeFileSync(`${dir}/pdf-${name}-${id}.pdf`,bytes);results.push({name,id,bytes:bytes.length,producer,loadedAmiriWeights:fonts});
 }
 const probe=await p.evaluate(async()=>{window.__pdfProbe=0;const {exportStoryToPdf}=await import('/lib/pdf-export.ts');const blob=await exportStoryToPdf('اختبار محلي','<p>نص <img src="data:image/png;base64,!" onerror="window.__pdfProbe=1"></p>',{fontSize:20,fontWeight:400,textAlign:'right',textColor:'#121A1B',paperStyleIndex:0},{bg:'#fff',text:'#121A1B',secondary:'#444'});return {handlerExecuted:window.__pdfProbe,bytes:blob.size};});assert.equal(probe.handlerExecuted,name==='after'?0:1);results.push({name,id:'injection-control',...probe});
 assert.deepEqual(errors,[]);await p.close();
 }fs.writeFileSync(dir+'/pdf-export-results-'+(process.env.PDF_SIDE||'both')+'-'+(process.env.PDF_CASE||'all')+'.json',JSON.stringify(results,null,2));console.log(results);}finally{await b.close();}})().catch(e=>{console.error(e.message);process.exitCode=1;});
