const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');
(async()=>{const b=await chromium.launch();try{const p=await b.newPage({viewport:{width:390,height:844},hasTouch:true});const errors=[];p.on('pageerror',e=>errors.push(e.message));let calls=0;
await p.route('**/api/gemini/generate',async route=>{calls++;const body=route.request().postDataJSON();let data;
if(body.useGoogleSearch){data={text:'مرجع تاريخي اختباري موثق.',model:'mock-provider',groundingMetadata:{groundingChunks:[{web:{uri:'https://example.org/reference',title:'مصدر اختباري'}}],groundingSupports:[{segment:{text:'مرجع تاريخي اختباري موثق.'},groundingChunkIndices:[0]}],searchEntryPoint:{renderedContent:'<div>Google Search — synthetic QA</div><script>parent.__badGrounding=1</script>'}}};}
else{const input=JSON.parse(body.contents[0].parts[0].text);const block=input.blocks[0];const evidence=[{blockId:block.id,quote:block.text}];data={text:JSON.stringify({summary:'تقرير اختبار مكتمل',findings:[{title:'ملاحظة اختبارية',detail:'وصف مسند بالنص',suggestion:'اقتراح لا يغير النص',evidence}],storyBible:[{name:'سلمى',facts:[{fact:'حقيقة اختبارية',evidence}]}]}),model:'mock-provider'};}
await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(data)});});
await p.goto((process.env.QA_URL||'http://localhost:3170')+'/tools/literary-analysis-check/');await p.waitForSelector('textarea');
for(const prompt of ['راجع استمرارية الشخصيات','حلل الإيقاع','اكشف ثغرات الحبكة','راجع الصوت الأدبي','تحقق من دقة هذه المعلومة التاريخية']){await p.locator('textarea').fill(prompt);await p.locator('button[aria-label="إرسال"]').click();await p.waitForFunction(()=>!document.querySelector('textarea').disabled);}
const result=await p.evaluate(()=>({sameHtml:document.querySelector('#story-content').innerHTML===window.__analysisQA.original,commits:window.__analysisQA.commits,bad:window.__badGrounding||0,text:document.body.textContent,reports:JSON.parse(localStorage.getItem('dar_alhikayat_ai_convs_story_qa-analysis-only')||'[]').flatMap(c=>c.messages).filter(m=>m.analysisReports?.length).length}));
assert.equal(calls,5);assert.equal(result.sameHtml,true);assert.equal(result.commits,0);assert.equal(result.bad,0);assert.equal(result.reports,5);assert(result.text.includes('مرجع تاريخي اختباري موثق.'));assert.equal(await p.locator('iframe').count(),1);assert.deepEqual(errors,[]);
await p.locator('iframe').scrollIntoViewIfNeeded();await p.screenshot({path:(process.env.QA_EVIDENCE||'/home/user/ai-tools-evidence')+'/analysis-browser.png'});
fs.writeFileSync((process.env.QA_EVIDENCE||'/home/user/ai-tools-evidence')+'/analysis-browser.json',JSON.stringify({requests:calls,originalHtmlPreserved:result.sameHtml,commits:result.commits,persistedReports:result.reports,iframeScriptDidNotExecute:result.bad===0,pageErrors:errors,provider:'intercepted synthetic responses; not a live model accuracy test'},null,2));console.log('PASS real Chromium: five tools, five persisted reports, unchanged editor HTML, zero commits, sandboxed search attribution');
}finally{await b.close();}})().catch(e=>{console.error(e.message);process.exitCode=1});
