const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');
(async()=>{const b=await chromium.launch();try{const p=await b.newPage({viewport:{width:390,height:844},hasTouch:true});const errors=[];p.on('pageerror',e=>errors.push(e.message));let calls=0;
await p.route('**/api/gemini/generate',async route=>{calls++;const body=route.request().postDataJSON();let data;
{const input=JSON.parse(body.contents[0].parts[0].text);const block=input.blocks[0];const evidence=[{blockId:block.id,quote:block.text}];data={text:JSON.stringify({summary:'تقرير اختبار للفقرة [b_one]',findings:[{title:'ملاحظة اختبارية',detail:'وصف مسند بالنص',suggestion:'اقتراح لا يغير النص',evidence}],storyBible:[{name:'سلمى',facts:[{fact:'حقيقة اختبارية',evidence}]}]}),model:'mock-provider'};}
await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(data)});});
await p.goto((process.env.QA_URL||'http://localhost:3170')+'/tools/literary-analysis-check/');await p.waitForSelector('textarea');
for(const prompt of ['بص على الشخصيات في النص وقولي رأيك من غير ما تغير حاجة','شوف إيقاع النص ومشاعر سلمى من غير تعديل','شوف الأحداث فيه ثغرات في الحبكة؟','راجع أسلوب الكلام حاسة إن نبرتها مختلفة']){await p.locator('textarea').fill(prompt);await p.locator('button[aria-label="إرسال"]').click();await p.waitForFunction(()=>!document.querySelector('textarea').disabled);}
const result=await p.evaluate(()=>({sameHtml:document.querySelector('#story-content').innerHTML===window.__analysisQA.original,commits:window.__analysisQA.commits,text:document.body.textContent,reports:JSON.parse(localStorage.getItem('dar_alhikayat_ai_convs_story_qa-analysis-only')||'[]').flatMap(c=>c.messages).filter(m=>m.analysisReports?.length).length}));
assert.equal(calls,4);assert.equal(result.sameHtml,true);assert.equal(result.commits,0);assert.equal(result.reports,4);assert(!result.text.includes('b_one'));assert.equal(await p.locator('iframe').count(),0);assert.deepEqual(errors,[]);
await p.screenshot({path:(process.env.QA_EVIDENCE||'/home/user/ai-tools-evidence')+'/analysis-browser.png'});
fs.writeFileSync((process.env.QA_EVIDENCE||'/home/user/ai-tools-evidence')+'/analysis-browser.json',JSON.stringify({requests:calls,originalHtmlPreserved:result.sameHtml,commits:result.commits,persistedReports:result.reports,rawParagraphIdsHidden:!result.text.includes('b_one'),searchFrames:0,pageErrors:errors,provider:'intercepted synthetic responses; not a live model accuracy test'},null,2));console.log('PASS real Chromium: four tools, four persisted reports, unchanged editor HTML, zero commits, no raw paragraph IDs');
}finally{await b.close();}})().catch(e=>{console.error(e.message);process.exitCode=1});
